language: python
os: linux
dist: focal
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10

jobs:
  include:
    - stage: check
      install: pip install $(grep -E "mypy|flake8" requirements.txt)
      script: make checks
    - stage: test
      install:
        - pip install -r requirements.txt
      script:
        - python setup.py build
        - pip install .
        - make tests
